version: '3.9'

services:
  db_admin:
    container_name: db_admin
    image: dpage/pgadmin4
    ports:
      - 9000:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: password
    networks:
      - new
  db:
    container_name: trenako_db
    image: postgres:13.3-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: trenako
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - postgres_data:/var/lib/postgres
    networks:
      - new
  webapi:
    container_name: webapi
    build: .docker/dev.dockerfile
    ports:
      - 80:5000
    environment:
      APP_PORT: 5000
      DATABASE_URL: postgresql://postgres:mysecretpassword@db/trenako
      SECRET_KEY: my-super-secret-key
    depends_on:
      - db
    networks:
      - new

volumes:
  postgres_data:
    driver: local

networks:
  new: