#!/bin/bash

echo "version = $1"

# Get version number from version tag
CRATE_VERSION=`echo $1 | cut -d'v' -f2`
echo "version = $CRATE_VERSION"

# Set new library version in Cargo.toml using set-cargo-version cli tool
# These new Cargo.toml and changelog.md generated by @semantic-release/changelog
# will be commit it by @semantic-release/git
set-cargo-version ./catalog/Cargo.toml $CRATE_VERSION
set-cargo-version ./collecting/Cargo.toml $CRATE_VERSION
set-cargo-version ./webapi/Cargo.toml $CRATE_VERSION


# Package the new library version and copy it to release folder
# These files will be upload to github by @semantic-release/github
mvn package
mkdir release && cp target/release/trenako-web-api release

printenv