[package]
name = "collecting"
version = "0.5.0"
authors = ["CarloMicieli <carlo.micieli@gmail.com>"]
edition = "2021"
license = "MIT"
rust-version = "1.59"

[dependencies]
thiserror = "1"
anyhow = "1"
