name: audit
on:
  pull_request:
    paths: Cargo.lock
  push:
    branches: main
    paths: Cargo.lock
  schedule:
    - cron: '58 23 * * *'

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: -D warnings

jobs:
  self-audit:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1

      - name: Setup the Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Cache cargo dependencies
        uses: Swatinem/rust-cache@v1    
  
      - name: Install cargo audit
        run: cargo install cargo-audit
      
      - name: Run cargo audit
        run: cargo audit --deny warnings