name: build
on: 
  push:
    branches-ignore: 
      - dev
      - main

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: -D warnings

jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
      - name: Check out the repocatalog
        uses: actions/checkout@v2

      - name: Setup the Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Cache cargo dependencies
        uses: Swatinem/rust-cache@v1

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test 
